# -*- coding: utf-8 -*-
"""Sentiment Analysis in 5 Lines

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZrVjLA6XfD5UTTOSWWU1vs4cbgCRdTVF
"""

from textblob import TextBlob

your_text = input("Enter the Text on which you want the Sentiment ")
sentiment_object  = TextBlob(your_text)
polarity_score = round(sentiment_object.sentiment.polarity,2)
subjectivity_score = round(sentiment_object.sentiment.subjectivity,2)
print("The Polarity of Sentiment of your Text is {} and Subjectivity of Your text is {} ".format( polarity_score , subjectivity_score))



